import Foundation

/// This protocol is used to annotate any dependency
/// that is part of the Composable Architecture.
/// Use this protocol in any struct or class to mark it as a dependency.
/// The dependency code is going to be autogenerated by Sourcery/
/// For example:
///
///     final class Networking {
///         // ... code
///     }
///
///     // Conform to the protocol
///     extension Networking: ComposableDependency {}
///
/// After a build the extension is going to be generated in the File.generated.
/// For example:
///
///     extension Networking: DependencyKey {
///         static var liveValue = Networking()
///     }
///
///     extension DependencyValues {
///         var networking: Networking {
///             get { self[Networking.self] }
///             set { self[Networking.self] = newValue }
///         }
///     }
///
protocol ComposableDependency {}
