
platform :ios do
  desc "Build and test the iOS project"
  lane :build_and_test do
    xcode_select("/Applications/Xcode_16.2.app")
    scan(
      workspace: "./Coffe.xcworkspace",                     
      destination: "platform=iOS Simulator,name=iPhone 16,OS=18.2",        
      clean: true                   
    )
  end
end