name: iOS Fastlane CI

on:
  pull_request:
    branches: [ "feature/ui_kit", "main", "feature/ui_kit_main" ]

jobs:
  build:
    runs-on: macos-14
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0.0'
          bundler-cache: true
      
      - name: Set Xcode version
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: CocoaPods
        run: bundle exec pod install

      - name: Build and test
        run: xcodebuild test -workspace Coffe.xcworkspace -scheme Coffe -destination "platform=iOS Simulator,OS=18.1,name=iPhone 16"
