name: iOS Fastlane CI

on:
  push:
    branches: [ "feature/ui_kit", "main", "feature/ui_kit_main" ]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.0

      - name: Install Fastlane
        run: gem install fastlane -NV

      - name: Run Fastlane build_and_test
        run: fastlane build_and_test
